apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd
  namespace: flux
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - args:
        - /usr/local/bin/etcd
        - --name
        - s1
        - --data-dir
        - /opt/etcd-data
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://0.0.0.0:2379
        - --listen-peer-urls
        - http://0.0.0.0:2380
        - --initial-advertise-peer-urls
        - http://0.0.0.0:2380
        - --initial-cluster
        - s1=http://0.0.0.0:2380
        - --initial-cluster-token
        - tkn
        - --initial-cluster-state
        - new
        image: quay.io/coreos/etcd:v3.3.9
        name: etcd
        volumeMounts:
          - name: etcd-data
            mountPath: /opt
        ports:
        - containerPort: 2379
        resources: {}
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: mypvc
      restartPolicy: Always
